services:
  minecraft:
    build: .
    container_name: minecraft-server
    ports:
      - "25565:25565"
      - "25575:25575"
    volumes:
      - ./server_data/world:/server/world
      - ./server_data/world_nether:/server/world_nether
      - ./server_data/world_the_end:/server/world_the_end
      - ./server_data/logs:/server/logs
